# Generated by Django 6.0.6 on 2026-07-02 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['label']},
        ),
    ]
